DELETE http://localhost:8080/api/demo/test-model/34
Accept: application/json

###
POST http://localhost:8080/api/demo/test-model
Content-Type: application/json

{
  "name": "név",
  "description": "null"
}
###

PUT http://localhost:8080/api/demo/test-model
Content-Type: application/json

{
  "name": "név",
  "description": "null"
}
###

###
GET http://localhost:8080/api/demo/test-model
Accept: application/json

###


GET http://localhost:8080/api/demo/test-model-param?id=101&name=Nééév
Accept: application/json

###


