POST http://localhost:8080/api/dog
Content-Type: application/json

{
  "name": "rénszarvi",
  "legsNumber": 14,
  "hornNumber": 17,
  "alma": "körte",
  "farmerID": 1
}

###

PUT http://localhost:8080/api/dog
Content-Type: application/json

{
  "id": 5,
  "name": "Fecske",
  "legsNumber": 14,
  "hornNumber": 17,
  "alma": "körte",
  "farmerID": 1
}

###
GET http://localhost:8080/api/dog
Accept: application/json

###

DELETE http://localhost:8080/api/dog/5
Accept: application/json

###

GET http://localhost:8080/api/dog/owner/1
Accept: application/json

###

GET http://localhost:8080/api/dog/2000
Accept: application/json

###

