POST http://localhost:8080/api/reindeer
Content-Type: application/json

{
  "name": "rénszarvi",
  "legsNumber": 14,
  "hornNumber": 17,
  "alma": "körte",
  "farmerID": 1
}

###

PUT http://localhost:8080/api/reindeer
Content-Type: application/json

{
  "id": 5,
  "name": "Fecske",
  "legsNumber": 14,
  "hornNumber": 17,
  "alma": "körte",
  "farmerID": 1
}

###
GET http://localhost:8080/api/reindeer
Accept: application/json

###

DELETE http://localhost:8080/api/reindeer/10
Accept: application/json

###

